# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170407_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_user_id',
        ),
    ]
