# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='city',
            field=models.CharField(blank=True, max_length=10, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='pref_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='ニックネーム'),
        ),
    ]
