# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170410_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='pref_code',
            field=models.IntegerField(verbose_name='都道府県'),
        ),
    ]
